# Generated by Django 5.2.16 on 2026-07-12 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_invoice_options_alter_order_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'درگاه پرداخت', 'verbose_name_plural': 'درگاه\u200cهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='ارائه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_pan',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره کارت ماسک\u200cشده'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'authority', 'reference_id'], name='payments_tr_status_0fdc0d_idx'),
        ),
    ]
