# Generated by Django 5.2.16 on 2026-07-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقایسه', 'verbose_name_plural': 'مقایسه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'علاقه\u200cمندی', 'verbose_name_plural': 'علاقه\u200cمندی\u200cها'},
        ),
    ]
