# Generated by Django 5.2.16 on 2026-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_contactmessage_newsletter_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='lovable_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات فرانت\u200cاند Lovable'),
        ),
    ]
