# Generated by Django 5.2.16 on 2026-07-12 19:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0002_alter_category_options_alter_productthreed_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkpriceupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'تغییر قیمت گروهی', 'verbose_name_plural': 'تغییرات قیمت گروهی'},
        ),
        migrations.AlterModelOptions(
            name='categorydiscount',
            options={'ordering': ['-created_at'], 'verbose_name': 'تخفیف دسته\u200cای', 'verbose_name_plural': 'تخفیف\u200cهای دسته\u200cای'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'کوپن', 'verbose_name_plural': 'کوپن\u200cها'},
        ),
        migrations.AlterField(
            model_name='bulkpriceupdate',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='bulk_price_updates', to='products.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='bulkpriceupdate',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('applied', 'اعمال\u200cشده'), ('canceled', 'لغوشده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
    ]
