# Generated by Django 5.2.16 on 2026-07-12 19:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referraltransaction'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orders', '0002_alter_invoice_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrank',
            options={'ordering': ['minimum_score', 'name'], 'verbose_name': 'رتبه مشتری', 'verbose_name_plural': 'رتبه\u200cهای مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'کد معرف', 'verbose_name_plural': 'کدهای معرف'},
        ),
        migrations.AlterModelOptions(
            name='referraltransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش معرفی', 'verbose_name_plural': 'تراکنش\u200cهای معرفی'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='customerrank',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.JSONField(blank=True, default=list, verbose_name='آدرس\u200cها'),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='کاربر معرفی\u200cشده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddConstraint(
            model_name='referraltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('referrer', models.F('referred_user')), _negated=True), name='referral_no_self_referral'),
        ),
    ]
