# Generated by Django 5.2.16 on 2026-07-16 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerrank_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='کلید دسترسی همکار / موبایل', max_length=150, verbose_name='عنوان کلید')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='کلید API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کلید API همکار/توسعه\u200cدهنده',
                'verbose_name_plural': 'کلیدهای API همکاران/توسعه\u200cدهندگان',
                'ordering': ['-created_at'],
            },
        ),
    ]
