# Generated by Django 6.0.7 on 2026-07-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='عمق')),
                ('color_scheme', models.CharField(blank=True, max_length=100, verbose_name='رنگ مد نظر')),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='custom_orders/', verbose_name='عکس مشتری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('quoted_price', models.BigIntegerField(default=0, verbose_name='قیمت پیشنهادی')),
                ('admin_notes', models.TextField(blank=True, verbose_name='توضیحات مدیر')),
                ('admin_voice', models.FileField(blank=True, null=True, upload_to='custom_orders/voices/', verbose_name='ویس مدیر')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام خریدار')),
                ('phone', models.CharField(max_length=11, verbose_name='تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('total_price', models.BigIntegerField(verbose_name='جمع کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name_fa', models.CharField(default='نیومون هوم', max_length=120, verbose_name='نام برند')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('primary_color', models.CharField(default='#0a1511', max_length=7, verbose_name='رنگ اصلی')),
                ('secondary_color', models.CharField(default='#c9a84c', max_length=7, verbose_name='رنگ طلایی')),
                ('hero_title', models.CharField(default='زیبایی', max_length=200, verbose_name='تیتر هیرو')),
                ('hero_subtitle', models.TextField(default='کالکشن جدید', verbose_name='زیرعنوان هیرو')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='عکس هیرو')),
                ('announcement_text', models.CharField(blank=True, max_length=255, verbose_name='متن متحرک')),
                ('is_installment_enabled', models.BooleanField(default=False, verbose_name='قسطی فعال؟')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='واتس\u200cاپ')),
                ('phone', models.CharField(default='۰۲۱', max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='نامک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': '۱. دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='نام عربی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='نامک (URL)')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت (ریال)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='قیمت دلاری ($)')),
                ('old_price', models.BigIntegerField(blank=True, default=0, verbose_name='قیمت قبل')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر اصلی')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='products/bg/', verbose_name='پس\u200cزمینه صفحه')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش در هوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': '۲. محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر گالری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان تنوع')),
                ('price_extra', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='تصویر تنوع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
