# Generated by Django 5.2.16 on 2026-07-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['name'], 'verbose_name': 'روش ارسال', 'verbose_name_plural': 'روش\u200cهای ارسال'},
        ),
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['province', 'city'], 'verbose_name': 'تعرفه ویژه ارسال', 'verbose_name_plural': 'تعرفه\u200cهای ویژه ارسال'},
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('shipping_method', 'province', 'city')},
        ),
    ]
