# Generated by Django 5.2.16 on 2026-07-12 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_bulkpriceupdate_options_and_more'),
        ('orders', '0001_initial'),
        ('shipping', '0002_alter_shippingmethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'تاریخچه وضعیت سفارش', 'verbose_name_plural': 'تاریخچه وضعیت سفارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت'), ('confirmed', 'تایید'), ('preparing', 'آماده\u200cسازی'), ('shipped', 'ارسال'), ('delivered', 'تحویل'), ('canceled', 'لغو'), ('returned', 'مرجوعی')], default='registered', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='گزینه\u200cهای انتخابی'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('registered', 'ثبت'), ('confirmed', 'تایید'), ('preparing', 'آماده\u200cسازی'), ('shipped', 'ارسال'), ('delivered', 'تحویل'), ('canceled', 'لغو'), ('returned', 'مرجوعی')], max_length=20, verbose_name='از وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('registered', 'ثبت'), ('confirmed', 'تایید'), ('preparing', 'آماده\u200cسازی'), ('shipped', 'ارسال'), ('delivered', 'تحویل'), ('canceled', 'لغو'), ('returned', 'مرجوعی')], max_length=20, verbose_name='به وضعیت'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number', 'status'], name='orders_orde_order_n_11231a_idx'),
        ),
    ]
