# Generated by Django 5.2.16 on 2026-07-16 14:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_invoice_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره استعلام')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='نام سفارش\u200cدهنده')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('inspiration_image', models.ImageField(blank=True, null=True, upload_to='orders/custom_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='تصویر نمونه/الهام\u200cبخش')),
                ('length_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='طول (سانتی\u200cمتر)')),
                ('width_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض (سانتی\u200cمتر)')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('wood_type', models.CharField(choices=[('raash', 'چوب راش طبیعی درجه یک'), ('gerdoo', 'چوب گردوی آمریکایی ممتاز'), ('baloot', 'چوب بلوط اروپایی'), ('roosi', 'چوب روسی ساب\u200cخورده'), ('other', 'سایر موارد (طبق توضیحات)')], default='raash', max_length=50, verbose_name='نوع چوب')),
                ('finish_type', models.CharField(choices=[('polyurethane', 'رنگ پلی\u200cاورتان مات/براق'), ('herbal_oil', 'روغن گیاهی طبیعی ضدآب'), ('patina', 'پاتینه و کهنه\u200cکاری دست\u200cساز'), ('raw', 'بدون پوشش (چوب خام)')], default='polyurethane', max_length=50, verbose_name='نوع رنگ/پوشش')),
                ('fabric_type', models.CharField(choices=[('velvet', 'مخمل وارداتی درجه یک'), ('leather', 'چرم طبیعی/صنعتی ممتاز'), ('linen', 'کتان / گونی\u200cبافت لوکس'), ('boucle', 'بوکله بافت\u200cدار اروپایی'), ('none', 'بدون پارچه (تمام چوب)')], default='velvet', max_length=50, verbose_name='جنس پارچه')),
                ('fabric_color_code', models.CharField(blank=True, max_length=100, verbose_name='کد/رنگ پارچه')),
                ('customer_notes', models.TextField(blank=True, verbose_name='توضیحات تکمیلی مشتری')),
                ('status', models.CharField(choices=[('pending_review', 'در انتظار بررسی تیم مهندسی'), ('quoted', 'برآورد قیمت و اعلام به مشتری'), ('accepted', 'تایید مشتری و پرداخت بیعانه'), ('wood_cutting', 'مرحله ۱: انتخاب و برش چوب'), ('carpentry', 'مرحله ۲: نجاری و کلاف\u200cبندی'), ('painting', 'مرحله ۳: رنگ\u200cآمیزی و پرداخت سطح'), ('upholstery', 'مرحله ۴: رویه\u200cکوبی و خیاطی پارچه'), ('quality_control', 'مرحله ۵: کنترل کیفیت نهایی'), ('ready', 'آماده ارسال / تحویل'), ('canceled', 'لغو شده')], default='pending_review', max_length=30, verbose_name='وضعیت ساخت')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ برآوردی (ریال)')),
                ('prepayment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ بیعانه (ریال)')),
                ('admin_feedback', models.TextField(blank=True, verbose_name='پاسخ و برآورد مهندسی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استعلام و سفارش اختصاصی',
                'verbose_name_plural': 'استعلام\u200cها و سفارش\u200cهای اختصاصی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_number', 'status'], name='orders_cust_request_a764d0_idx')],
            },
        ),
    ]
