# Generated by Django 5.2.16 on 2026-07-12 19:01

import django.db.models.deletion
from django.db import migrations, models
try:
    import ckeditor.fields
    RichTextField = ckeditor.fields.RichTextField
except ImportError:
    RichTextField = models.TextField


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='productthreed',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل سه\u200cبعدی محصول', 'verbose_name_plural': 'فایل\u200cهای سه\u200cبعدی محصولات'},
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_slug_3edc0c_idx',
            old_name='products_pr_slug_6f31be_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_sku_ca0cdc_idx',
            old_name='products_pr_sku_904f20_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_2fee29_idx',
            old_name='products_pr_is_acti_f4a354_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='فیلدهای شخصی\u200cسازی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productthreed',
            name='file',
            field=models.FileField(upload_to='products/3d/', verbose_name='فایل سه\u200cبعدی'),
        ),
        migrations.AlterField(
            model_name='productthreed',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/3d/previews/', verbose_name='تصویر پیش\u200cنمایش'),
        ),
    ]
