# Generated by Django 5.2.16 on 2026-07-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_productthreed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthreed',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_d_files', to='products.product', verbose_name='محصول'),
        ),
    ]
